# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 3D Printing, ESP32, docker and other things ...
email: security@gillet.ninja
description: >- # this means to ignore newlines until "baseurl:"
  Security, Energy, 3D printing and IOT.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://somm15.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: somm15
github_username:  somm15
locale: "en"
name: "Simon Gillet"
timezone: "Europe/Brussels"
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: false
      comments: false
      share: true
      related: true
      author_profile: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

author:
  name     : "Simon Gillet"
  avatar   : "/assets/images/avataaars.png"
  bio      : "Cyber Security Engineer"
  location : "Belgium"
  links:
    - label: "PGP"
      icon: "fab fa-fw fa-key"
      url: "/assets/simon_gillet.asc"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/somm15"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/somm15"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/simon-gillet-71a53422/"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-131084208-1"
    anonymize_ip: false # default

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/somm15"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/somm15"
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

